  module.exports = {
    SUCESSO: 'SUCESSO',
  
    JA_BAIXADO: 'JA_BAIXADO',
  
    ERRO_CONSULTA: 'ERRO_CONSULTA',
  
    ERRO_ATUALIZACAO: 'ERRO_ATUALIZACAO',
  
    ERRO_BAIXA: 'ERRO_BAIXA',
  
    ERRO_DESCONHECIDO: 'ERRO_DESCONHECIDO'
  };